Update nodejs.yml
Currently our build is failing because of the following issue: 
```
./src/utilities/fonts.scss
Error: resolve-url-loader: CSS error
  Invalid mapping: {"generated":{"line":1,"column":69},"source":"file:///home/runner/work/Caravan/Caravan/src/utilities/fonts.scss","original":{"column":null},"name":null}
```
I believe that this will be fixed by adding an enviorment variable that will allow SASS imports to be used.